/* eslint-disable @typescript-eslint/no-explicit-any */
import { Users, Award, Globe, Clock, MessageCircle, CalendarCheck, Plane, Car, Compass, Heart, ShieldCheck, MapPin, Phone, Mail } from "lucide-react";

const stats = [[Users,"10,000+","Happy travellers"],[Award,"5+","Years of service"],[Globe,"50+","Sri Lanka routes"],[Clock,"24/7","Travel support"]];
const services = [[Plane,"Airport Transfers","Private pickup and drop-off from Katunayake Airport to major destinations."],[Car,"Vehicle Rentals","Cars and scooters for flexible local trips and longer travel plans."],[Compass,"Safari & Tours","Safari parks, day tours, and custom Sri Lanka itineraries."]];
const values = [[Heart,"Traveller First","We keep the booking process simple and focus on what travellers need most: clear communication, comfort, and reliability."],[ShieldCheck,"Safe, Practical Travel","Routes, vehicles, pickup times, and driver details are handled with care so your trip feels organized."],[MapPin,"Local Route Knowledge","From Ella to Yala, Kandy, Galle, and airport transfers, we help choose routes that make sense for your schedule."]];

export default function About(){return <>
  <section className="hero hero-split" style={{backgroundImage:"url('https://images.pexels.com/photos/18826647/pexels-photo-18826647.jpeg?auto=compress&cs=tinysrgb&w=1800')"}}><div className="container hero-grid"><div><span className="eyebrow">Local travel support in Sri Lanka</span><h1>About Radesha Tours</h1><p>We help travellers arrange private airport transfers, vehicle rentals, safari tours, and custom routes across Sri Lanka with clear communication and easy WhatsApp booking.</p><div className="actions"><a className="btn btn-green" href="https://wa.me/94758110086"><MessageCircle size={16}/>Contact on WhatsApp</a><a className="btn btn-outline" href="#story">Read our story</a></div></div><div className="about-stats">{stats.map(([Icon,value,label]:any)=><div className="about-stat" key={value}><Icon/><b>{value}</b><span>{label}</span></div>)}</div></div></section>

  <section id="story" className="section"><div className="container hero-grid"><div><div className="eyebrow">Our story</div><h2>Built for travellers who want a smoother Sri Lanka trip</h2><p>Radesha Tours started with a simple idea: make local transport and tour planning easier for visitors. Today, we arrange airport pickups, city transfers, vehicle rentals, safari tours, and custom travel routes with practical local guidance.</p><p>Our work is direct and personal. You message us, share the trip details, and we help shape the right option for your route, timing, luggage, and travel style.</p></div><div className="card how-card"><div className="how-title"><CalendarCheck/><span><h3>How we help</h3><p>Simple planning, useful advice, reliable travel.</p></span></div>{['Tell us your pickup location, destination, dates, and group size','We suggest the best route, vehicle, timing, and price','Confirm on WhatsApp and travel with local support'].map((x,i)=><div className="how-step" key={x}><b>{i+1}</b><span>{x}</span></div>)}</div></div></section>

  <section className="section section-muted"><div className="container"><div className="about-centered"><div className="eyebrow" style={{color:'#f46b2b'}}>What we do</div><h2>Travel services with one clear contact point</h2></div><div className="cards-3">{services.map(([Icon,title,text]:any)=><div className="card card-body about-service" key={title}><Icon/><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>

  <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Our values</div><h2>The details that make travel feel easy</h2></div><p>Good travel support is not only about the vehicle. It is also about timing, communication, route decisions, and trust.</p></div><div className="cards-3">{values.map(([Icon,title,text]:any)=><div className="card card-body value-card" key={title}><Icon/><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>

  <section className="section section-dark"><div className="container hero-grid"><div><div className="eyebrow">Contact details</div><h2>Message us before your trip</h2><p>Share your dates, route, passenger count, and travel preferences. We will help you choose the right transfer, rental, or tour.</p></div><div className="feature-list"><div className="dark-card"><Phone/><h3>Phone / WhatsApp</h3><p>+94 75 811 0086</p></div><div className="dark-card"><Mail/><h3>Email</h3><p>info@radeshatours.com</p></div><div className="dark-card"><MapPin/><h3>Service Area</h3><p>Ella, airport routes, and Sri Lanka tours</p></div><div className="dark-card"><Clock/><h3>Availability</h3><p>Daily travel support</p></div></div></div></section>

  <section className="cta"><div className="container cta-row"><div><h2>Start your journey with Radesha Tours</h2><p>Tell us what you need and we will help plan the next step.</p></div><a className="btn btn-light" href="https://wa.me/94758110086"><MessageCircle size={16}/>Contact us on WhatsApp</a></div></section>
  </>}
