/* eslint-disable @typescript-eslint/no-explicit-any */
import { Link } from "react-router-dom";
import { Plane, Clock, ShieldCheck, MapPin, CheckCircle2, Users, Briefcase, MessageCircle, CalendarCheck, Car } from "lucide-react";
const routes=[['Colombo','35 km','$18'],['Kandy','115 km','$50'],['Galle','150 km','$50'],['Ella','260 km','$100']];
const included=['Professional local chauffeurs','Flight arrival tracking','Meet and greet at the airport','Private, air-conditioned vehicles','Flexible pickup for delays','Custom routes across Sri Lanka'];
export default function AirportTransfer(){return <>
 <section className="hero hero-split" style={{backgroundImage:"url('https://images.pexels.com/photos/2574078/pexels-photo-2574078.jpeg?auto=compress&cs=tinysrgb&w=1800')"}}><div className="container hero-grid"><div><span className="eyebrow">Katunayake Airport pickup and drop-off</span><h1>Reliable airport transfers across Sri Lanka</h1><p>Start or finish your trip with a private transfer from Bandaranaike International Airport to Ella, Kandy, Galle, Colombo, Yala, Arugam Bay, and more.</p><div className="actions"><a className="btn btn-green" href="https://wa.me/94758110086"><MessageCircle size={16}/>Book on WhatsApp</a><Link className="btn btn-outline" to="/hire-rates">See fixed route rates →</Link></div></div><div className="quote-panel"><small>TRANSFER QUOTE</small><h3>Send these details</h3>{['Arrival date and time','Flight number','Destination or hotel name','Passengers and luggage count'].map(x=><div className="quote-item" key={x}>{x}</div>)}<a className="btn btn-light" style={{width:'100%',marginTop:8}} href="https://wa.me/94758110086">Request a quick quote</a></div></div></section>
 <div className="trust-strip"><div className="container trust-grid"><div className="trust-item"><Clock/>Fixed prices before you travel</div><div className="trust-item"><Users/>Private rides for solo travellers, couples, and groups</div><div className="trust-item"><Car/>Clean vehicles and friendly local support</div><div className="trust-item"><Plane/>Flight-aware pickups</div></div></div>
 <section className="section section-muted"><div className="container"><div className="section-head"><div><div className="eyebrow">Popular routes</div><h2>Airport transfer prices at a glance</h2></div><p>These sample fares help you plan quickly. For exact vehicle availability, pickup timing, and custom destinations, message us directly.</p></div><div className="cards-4">{routes.map(r=><div className="card route-card" key={r[0]}><div className="route-top"><MapPin size={18} color="#079db7"/><span>{r[1]}</span></div><h3>{r[0]}</h3><div className="price">{r[2]}</div><p className="muted">From Katunayake Airport</p><a className="btn btn-dark" style={{width:'100%',marginTop:18}} href={`https://wa.me/94758110086?text=Airport%20transfer%20to%20${r[0]}`}>Book this route</a></div>)}</div></div></section>
 <section className="section"><div className="container hero-grid"><div><div className="eyebrow" style={{color:'#f46b2b'}}>Included service</div><h2>More than just a ride from the airport</h2><p>We focus on making the arrival moment calm: clear pickup instructions, a suitable vehicle, and a driver who understands the route before you land.</p></div><div className="feature-list">{included.map(x=><div className="feature-box" key={x}><CheckCircle2/><b>{x}</b></div>)}</div></div></section>
 <section className="section section-dark"><div className="container"><div style={{textAlign:'center',marginBottom:35}}><div className="eyebrow">How booking works</div><h2>Simple confirmation in three steps</h2></div><div className="cards-3">{[['1','Share arrival details','Send flight number, date, passenger count, and destination.'],['2','Get your quote','We confirm the route, vehicle type, pickup point, and price.'],['3','Meet your driver','Your driver will be ready for a smooth onward journey.']].map(s=><div className="dark-card" key={s[0]}><b className="price" style={{fontSize:18}}>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></div></section>
 <section className="section"><div className="container cards-4">{[[Clock,'On-Time Pickup'],[ShieldCheck,'Safe Private Ride'],[Briefcase,'Luggage Friendly'],[MessageCircle,'Easy WhatsApp Booking']].map(([Icon,title]:any)=><div className="card card-body" key={title}><Icon color="#079db7"/><h3 style={{marginTop:16}}>{title}</h3><p>Practical planning and friendly support for a comfortable transfer.</p></div>)}</div></section>
 <section className="cta"><div className="container cta-row"><div><h2>Need an airport transfer?</h2><p>Send your flight number, destination, date, passengers, and bags.</p></div><a className="btn btn-light" href="https://wa.me/94758110086"><CalendarCheck size={16}/>Book your transfer</a></div></section>
 </>}
