/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from "react";
import { MapPin, Search, ShieldCheck, Clock, MessageCircle, CheckCircle2, Car, Route } from "lucide-react";
const cities=[['Colombo',35,'$18'],['Bentota',105,'$50'],['Galle',150,'$50'],['Hikkaduwa',140,'$54'],['Unawatuna',155,'$52'],['Ahangama',165,'$57'],['Midigama',170,'$57'],['Weligama',175,'$58'],['Mirissa',180,'$60'],['Matara',190,'$65'],['Hiriketiya',210,'$67'],['Hambantota',240,'$85'],['Tissamaharama (Tissa)',260,'$90'],['Yala',290,'$90'],['Kataragama',270,'$95'],['Arugam Bay',360,'$120'],['Ella',260,'$100'],['Pasikuda',300,'$110'],['Trincomalee (Trinco)',250,'$100'],['Nuwara Eliya',175,'$75'],['Hatton',140,'$65'],['Kandy',115,'$50'],['Sigiriya',170,'$60']];
export default function Hire(){const [search,setSearch]=useState('');const results=cities.filter(c=>String(c[0]).toLowerCase().includes(search.toLowerCase()));return <>
 <section className="hero hero-split" style={{backgroundImage:"url('https://images.pexels.com/photos/46148/aircraft-jet-landing-cloud-46148.jpeg?auto=compress&cs=tinysrgb&w=1800')"}}><div className="container hero-grid"><div><span className="eyebrow">Airport to traveller rates</span><h1>Fixed transfer prices from Katunayake Airport</h1><p>Search popular Sri Lankan destinations, compare starting prices, and book a private airport transfer directly on WhatsApp.</p><div className="actions"><a className="btn btn-green" href="#routes">Request transfer</a><a className="btn btn-outline" href="#routes">Browse rates →</a></div></div><div className="quote-panel"><small>QUICK HIGHLIGHTS</small><div className="cards-2 feature-list" style={{marginTop:12}}>{[['23','routes listed'],['24/7','airport pickup'],['Fixed','route pricing'],['Private','vehicle service']].map(x=><div className="quote-item" key={x[0]}><b>{x[0]}</b><br/><span>{x[1]}</span></div>)}</div></div></div></section>
 <div className="trust-strip"><div className="container trust-grid"><div className="trust-item"><MapPin/>Fixed pricing</div><div className="trust-item"><MessageCircle/>Quick booking</div><div className="trust-item"><ShieldCheck/>Safe travel</div><div className="trust-item"><Clock/>Flight aware</div></div></div>
 <section id="routes" className="section section-muted"><div className="container"><div className="section-head"><div><div className="eyebrow">Route finder</div><h2>Browse airport transfer rates</h2><p>Prices below are starting rates from Katunayake Airport. Final confirmation depends on date, pickup time, passengers, luggage, and vehicle availability.</p></div><label style={{position:'relative',minWidth:320}}><Search size={17} style={{position:'absolute',left:13,top:13,color:'#8b96a3'}}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search destination..." style={{width:'100%',padding:'12px 12px 12px 40px',border:'1px solid #dce3e9',borderRadius:5}}/></label></div><div className="tabs"><span className="tab">All routes</span><span className="tab">Nearby</span><span className="tab">Ella</span><span className="tab">Galle</span></div><p className="muted">Showing {results.length} of {cities.length} routes</p><div className="route-grid">{results.map(c=><div className="card route-card" key={c[0]}><div className="route-top"><MapPin size={18} color="#079db7"/><span>{c[1]} km</span></div><h3>{c[0]}</h3><p className="muted">From Katunayake Airport</p><div style={{background:'#f5f7f9',padding:12,marginTop:15}}><span className="muted">Starting price</span><div className="price">{c[2]}</div></div><a className="btn btn-dark" href={`https://wa.me/94758110086?text=Book%20transfer%20to%20${c[0]}`}><Car size={14}/>Book Transfer</a></div>)}</div></div></section>
 <section className="section"><div className="container hero-grid"><div><div className="eyebrow" style={{color:'#f46b2b'}}>Before you book</div><h2>A smoother airport pickup starts with the right details</h2><p>Send your arrival date, flight number, destination, passenger count, and luggage count. We will confirm the pickup plan and best vehicle for your group.</p><a className="btn btn-green" href="https://wa.me/94758110086">Send travel details</a></div><div className="feature-list">{['Arrival date and time','Flight number','Hotel or destination','Passengers and luggage','Child seat request','Return transfer needs'].map(x=><div className="feature-box"><CheckCircle2/>{x}</div>)}</div></div></section>
 <section className="section section-dark"><div className="container hero-grid"><div><div className="eyebrow">Why book with us</div><h2>Private transfer support</h2><p>We help travellers avoid confusing airport arrivals with clear pickup instructions, private vehicles, and local route advice.</p></div><div className="feature-list">{[[Car,'Solo, family, and group rides'],[ShieldCheck,'Licensed, careful drivers'],[Clock,'Flexible timing'],[Route,'Custom route quotes']].map(([Icon,t]:any)=><div className="dark-card"><Icon/><h3>{t}</h3><p>Reliable support for every airport journey.</p></div>)}</div></div></section>
 <section className="cta"><div className="container cta-row"><div><h2>Ready to reserve your airport transfer?</h2><p>Send your route and flight details for a quick confirmation.</p></div><a className="btn btn-light" href="https://wa.me/94758110086">Book on WhatsApp</a></div></section>
 </>}
