import { Link } from "react-router-dom";
import { Car, Plane, Compass, ShieldCheck, Clock3, BadgeDollarSign, MapPin, MessageCircle, Star, Route, CalendarCheck, Phone, Mail, Navigation } from "lucide-react";

const services=[
  {title:"Vehicle Rentals",text:"Cars, scooters, and comfortable private vehicles for exploring Ella and beyond at your own pace.",link:"/rent-vehicles",img:"/vehicle-rental-hero.jpeg"},
  {title:"Airport Transfers",text:"Reliable pickups from Katunayake Airport with fixed route pricing, flight tracking, and friendly drivers.",link:"/airport-transfer",img:"https://images.pexels.com/photos/2574078/pexels-photo-2574078.jpeg?auto=compress&cs=tinysrgb&w=900"},
  {title:"Safari & Day Tours",text:"Plan Yala, Udawalawe, Kumana, Ella viewpoints, waterfalls, tea country, and custom Sri Lanka trips.",link:"/safari",img:"https://images.pexels.com/photos/37114883/pexels-photo-37114883.jpeg?auto=compress&cs=tinysrgb&w=900"},
];
const routes=[['Ella','260 km','$100'],['Kandy','115 km','$50'],['Galle','150 km','$50'],['Arugam Bay','360 km','$120']];
export default function Home(){return <>
  <section className="hero hero-home"><div className="container"><span className="eyebrow">Ella-based travel service for all of Sri Lanka</span><h1>Ella Tours, Transfers & Rentals Across Sri Lanka</h1><p>Radesha Tours is based in Ella and offers island-wide airport transfers, private tours, safari trips, car rentals, and scooter rentals with local support from pickup to drop-off.</p><div className="actions"><a className="btn btn-green" href="https://wa.me/94758110086"><MessageCircle size={16}/>Plan on WhatsApp</a><Link className="btn btn-outline" to="/hire-rates">View transfer rates →</Link></div><div className="hero-stats"><div><b>24/7</b><span>Booking support</span></div><div><b>✈</b><span>Airport routes</span></div><div><b>3</b><span>Core services</span></div></div></div></section>
  <div className="trust-strip"><div className="container trust-grid"><div className="trust-item"><MapPin/>Airport pickup from Katunayake</div><div className="trust-item"><Route/>Ella, Yala, Kandy, Galle & island-wide</div><div className="trust-item"><CalendarCheck/>Fast booking through WhatsApp</div><div className="trust-item"><ShieldCheck/>Private, licensed travel</div></div></div>
  <section className="section section-muted"><div className="container"><div className="section-head"><div><div className="eyebrow">What we arrange</div><h2>Travel services built around your route</h2></div><p>Whether you need a quick airport pickup, a scooter for Ella, or a safari day planned from start to finish, the booking flow stays simple and direct.</p></div><div className="cards-3">{services.map((s,i)=><Link to={s.link} className="card" key={s.title}><img className="service-img" src={s.img} alt={`${s.title} service in Sri Lanka`} loading="lazy" width="900" height="520"/><div className="card-body"><div style={{color:['#1775ed','#00a6bd','#ff7315'][i]}}>{i===0?<Car/>:i===1?<Plane/>:<Compass/>}</div><h3>{s.title}</h3><p>{s.text}</p><span className="learn">Learn more →</span></div></Link>)}</div></div></section>
  <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow" style={{color:'#f46b2b'}}>Popular airport routes</div><h2>Start with a clear transfer price</h2><p>Browse fixed rates from Katunayake Airport to major destinations, then confirm your pickup time, luggage needs, and vehicle by WhatsApp.</p><Link className="btn btn-dark" to="/hire-rates">Browse all routes</Link></div><div className="cards-2"></div></div><div className="cards-4">{routes.map(r=><div className="card route-card" key={r[0]}><div className="route-top"><MapPin size={18} color="#079db7"/><span>{r[1]}</span></div><h3>{r[0]}</h3><div className="price">{r[2]}</div><p className="muted">Starting from Katunayake Airport</p></div>)}</div></div></section>
  <section className="section section-dark"><div className="container"><div className="hero-grid"><div><div className="eyebrow">Why travellers choose us</div><h2>Local travel help without complicated booking forms</h2><p>Tell us where you want to go. We help match the route, timing, vehicle, and driver to your arrival or day tour before you confirm.</p><ol className="checks"><li>Send your travel dates and pickup location</li><li>Get a clear route and vehicle recommendation</li><li>Confirm on WhatsApp and enjoy the journey</li></ol></div><div className="feature-list"><div className="dark-card"><ShieldCheck/><h3>Safe & Licensed</h3><p>Maintained vehicles, insured trips, and careful local drivers.</p></div><div className="dark-card"><Clock3/><h3>24/7 Travel Help</h3><p>Early airport arrivals, late transfers, and quick WhatsApp replies.</p></div><div className="dark-card"><BadgeDollarSign/><h3>Clear Prices</h3><p>Route rates and custom quotes explained before you book.</p></div><div className="dark-card"><Route/><h3>Flexible Routes</h3><p>Custom destinations and stops across Sri Lanka.</p></div></div></div></div></section>
  <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Flexible trip planning</div><h2>Need a custom Sri Lanka itinerary?</h2><p>Combine airport transfers, Ella sightseeing, safari parks, cultural stops, and beach routes into one private travel plan.</p></div><div className="card card-body"><div style={{color:'#f4a900'}}><Star fill="currentColor" size={17}/> ★ ★ ★ ★</div><h3>Fast replies, flexible pickup times</h3><p>Practical local advice for travellers arriving in Sri Lanka.</p></div></div></div></section>
  <section className="section section-muted google-reviews"><div className="container"><div className="section-head"><div><div className="eyebrow" style={{color:'#f46b2b'}}>Google reviews</div><h2>See what travellers say about Radesha Tours</h2><p>Read recent customer feedback on our official Google business profile. Google displays the current rating, review count, and full review text directly on the listing.</p></div><div className="google-review-badge"><span className="google-g">G</span><div><b>Radesha Tours on Google</b><small>Verified customer feedback</small></div></div></div><div className="review-actions-grid"><article className="card card-body review-action"><Star/><h3>Read our Google reviews</h3><p>Open the Radesha Tours Google listing to see the latest ratings, photos, and comments from travellers.</p><a className="learn" href="https://www.google.com/maps?cid=18185079200350651262" target="_blank" rel="noreferrer">View reviews on Google →</a></article><article className="card card-body review-action"><MessageCircle/><h3>Share your experience</h3><p>Travelled with us? Open our Google profile, select Reviews, and leave your honest feedback.</p><a className="learn" href="https://www.google.com/maps?cid=18185079200350651262" target="_blank" rel="noreferrer">Write a Google review →</a></article><article className="card card-body review-action"><MapPin/><h3>Find us on Google Maps</h3><p>View the verified business location, get directions, and contact Radesha Tours from Google Maps.</p><a className="learn" href="https://www.google.com/maps?cid=18185079200350651262" target="_blank" rel="noreferrer">Open Google Maps →</a></article></div></div></section>
  <section className="section section-dark location-section"><div className="container"><div className="section-head"><div><div className="eyebrow">Find us on the map</div><h2>Radesha Tours location details</h2><p>Use the map to find our exact business location, get directions, and share your pickup point when planning a transfer, rental, or custom tour.</p></div></div><div className="location-grid"><div className="location-details"><div className="location-row"><Phone/><span><small>PHONE / WHATSAPP</small><a href="tel:+94758110086">+94 75 811 0086</a></span></div><div className="location-row"><Mail/><span><small>EMAIL</small><a href="mailto:info@radeshatours.com">info@radeshatours.com</a></span></div><div className="location-row"><MapPin/><span><small>BUSINESS</small><b>Radesha Tours, Ella, Sri Lanka</b></span></div><div className="actions"><a className="btn btn-light" href="https://www.google.com/maps/search/?api=1&query=6.7405271,81.1025864" target="_blank" rel="noreferrer"><Navigation size={15}/>Get directions</a><a className="btn btn-green" href="https://wa.me/94758110086" target="_blank" rel="noreferrer"><MessageCircle size={15}/>WhatsApp</a></div></div><div className="map-wrap"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d613.2959688102432!2d81.1025864!3d6.7405271!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae46b00452576e5%3A0xfc5e612f1d3ec37e!2sRadesha%20Tours!5e1!3m2!1sen!2slk!4v1786413022624!5m2!1sen!2slk" title="Radesha Tours location on Google Maps" allowFullScreen loading="lazy" referrerPolicy="strict-origin-when-cross-origin"/></div></div></div></section>
  <section className="cta"><div className="container cta-row"><div><h2>Ready to plan your ride or tour?</h2><p>Send your pickup point, destination, date, and passenger count.</p></div><a className="btn btn-light" href="https://wa.me/94758110086"><MessageCircle size={16}/>Chat on WhatsApp</a></div></section>
  </>}
