/* eslint-disable @typescript-eslint/no-explicit-any */
import { Camera, Clock, Users, Eye, MessageCircle, CheckCircle2, MapPin, Car, Route } from "lucide-react";
const tours=[
 ['Half-Day Safari','Yala or Udawalawe','From $150','4–5 hours','orange',['Morning or afternoon slot','Experienced safari guide','Private jeep options','Wildlife viewing']],
 ['Full-Day Safari','Yala, Udawalawe, or Kumana','From $280','8–10 hours','green',['All-day safari adventure','Lunch stop planning','Multiple park zones','Photography opportunities']],
 ['Sunset Safari','Selected safari routes','From $180','3–5 hours','amber',['Evening expedition','Golden-hour photos','Relaxed safari pace','Great for couples']],
 ['Sri Lanka Safari Tour','Yala, Udawalawe, Bundala, Kumana','Contact on WhatsApp','Flexible','green',['Multiple national parks','Private safari jeep','Park and route guidance','Pickup from your location']],
 ['Sri Lanka Day Tour','Safari or cultural route','Contact on WhatsApp','1 day','blue',['Custom day route','Private vehicle with driver','Flexible departure time','Local recommendations']],
 ['Monthly Island Tour','Island-wide','Contact on WhatsApp','30 days','purple',['Island-wide safari and travel','Transport and guide support','Flexible itinerary planning','Ideal for long stays']],
];
export default function Safari(){return <>
 <section className="hero hero-split" style={{backgroundImage:"url('https://images.pexels.com/photos/37114883/pexels-photo-37114883.jpeg?auto=compress&cs=tinysrgb&w=1800')"}}><div className="container hero-grid"><div><span className="eyebrow">Private safari tours in Sri Lanka</span><h1>Safari adventures planned around your journey</h1><p>Explore Yala, Udawalawe, Bundala, Kumana, and custom day tours with private transport, local guidance, and simple WhatsApp booking.</p><div className="actions"><a className="btn btn-green" href="https://wa.me/94758110086">Book on WhatsApp</a><a className="btn btn-outline" href="#tours">View safari options →</a></div></div><div className="quote-panel"><small>GOOD TO KNOW</small><div className="feature-list" style={{marginTop:12}}>{[['4','major parks'],['Half','or full day'],['Private','jeep options'],['Custom','pickup plans']].map(x=><div className="quote-item"><b>{x[0]}</b><br/><span>{x[1]}</span></div>)}</div><p style={{fontSize:11,color:'#fff'}}>Tell us your pickup location, date, group size, and preferred park. We will help suggest the best safari timing.</p></div></div></section>
 <div className="trust-strip"><div className="container trust-grid"><div className="trust-item"><Camera/>Photography moments</div><div className="trust-item"><Clock/>Best time guidance</div><div className="trust-item"><Users/>Private trip support</div><div className="trust-item"><Eye/>Wildlife spotting</div></div></div>
 <section id="tours" className="section section-muted"><div className="container"><div className="section-head"><div><div className="eyebrow" style={{color:'#f46b2b'}}>Choose your safari</div><h2>Safari tours for different travel styles</h2></div><p>Pick a ready-made option or message us for a custom plan with pickup, jeep, route timing, and park recommendations.</p></div><div className="cards-3">{tours.map(t=><div className="safari-card" key={String(t[0])}><div className={`safari-top ${t[4]}`}><Eye size={22}/><h3>{t[0]}</h3><small>{t[1]}</small><div className="price">{t[2]}</div><small>◷ {t[3]}</small></div><div className="safari-body"><ul className="checks">{(t[5] as string[]).map(x=><li key={x}>{x}</li>)}</ul><a className="btn btn-dark" href={`https://wa.me/94758110086?text=${encodeURIComponent('Ask about '+t[0])}`}><MessageCircle size={14}/>Ask about this tour</a></div></div>)}</div></div></section>
 <section className="section"><div className="container hero-grid"><div><div className="eyebrow" style={{color:'#149c4e'}}>Park options</div><h2>Choose the park that fits your route</h2><p>If you are staying in Ella, on the south coast, or heading east, we can help you decide which park makes the most sense for travel time, wildlife goals, and your schedule.</p><a className="btn btn-green" href="https://wa.me/94758110086">Ask for park advice</a></div><div className="feature-list">{[['Yala National Park','Leopards, elephants, and dramatic dry-zone landscapes'],['Udawalawe National Park','Elephants, open plains, and reliable wildlife viewing'],['Bundala National Park','Birdlife, wetlands, coastal scenery, and quiet routes'],['Kumana National Park','Birds, wild landscapes, and east-coast safari routes']].map(x=><div className="feature-box"><MapPin/><span><b>{x[0]}</b>{x[1]}</span></div>)}</div></div></section>
 <section className="section section-dark"><div className="container hero-grid"><div><div className="eyebrow" style={{color:'#f28b35'}}>What to expect</div><h2>A safari day planned with practical local details</h2><p>We help coordinate pickup time, park choice, safari duration, jeep options, and onward transport so the day feels organized before it starts.</p></div><div className="feature-list">{[[Route,'Pickup planning'],[Car,'Comfortable travel'],[Camera,'Photo-friendly timing'],[CheckCircle2,'Custom itinerary']].map(([Icon,t]:any)=><div className="dark-card"><Icon/><h3>{t}</h3><p>Thoughtful details for a smooth safari day.</p></div>)}</div></div></section>
 <section className="cta" style={{background:'linear-gradient(90deg,#ff7109,#e78a00)'}}><div className="container cta-row"><div><h2>Ready to plan your safari?</h2><p>Send your date, pickup location, group size, and preferred park.</p></div><a className="btn btn-light" href="https://wa.me/94758110086"><MessageCircle size={16}/>Book safari on WhatsApp</a></div></section>
 </>}
