import { Link } from "react-router-dom";
import { CheckCircle2, Clock, MapPin, MessageCircle, Car } from "lucide-react";
import { SeoHead } from "../components/SeoHead";
import Breadcrumbs from "../components/Breadcrumbs";

type RouteInfo={slug:string;destination:string;distance:string;duration:string;description:string};
const routeData:Record<string,RouteInfo>={
 "colombo-airport-to-ella":{slug:"colombo-airport-to-ella",destination:"Ella",distance:"Approximately 260 km",duration:"Journey time depends on traffic, weather, and chosen route",description:"Travel privately from Bandaranaike International Airport to Ella with pickup coordinated around your flight and a route planned for Sri Lanka’s hill country."},
 "colombo-airport-to-kandy":{slug:"colombo-airport-to-kandy",destination:"Kandy",distance:"Approximately 115 km",duration:"Journey time varies with traffic and pickup time",description:"Arrange a direct private airport transfer to Kandy with space planned around your passenger and luggage requirements."},
 "colombo-airport-to-galle":{slug:"colombo-airport-to-galle",destination:"Galle",distance:"Approximately 150 km",duration:"Journey time varies by road conditions",description:"Book a private arrival transfer from Colombo Airport to historic Galle and the southern coast with clear pickup instructions."},
 "colombo-airport-to-mirissa":{slug:"colombo-airport-to-mirissa",destination:"Mirissa",distance:"Approximately 180 km",duration:"Journey time varies by traffic and route",description:"Continue from the airport to Mirissa with a private vehicle, luggage space, and direct communication before arrival."},
 "colombo-airport-to-arugam-bay":{slug:"colombo-airport-to-arugam-bay",destination:"Arugam Bay",distance:"Approximately 360 km",duration:"A long-distance transfer; confirm timing when booking",description:"Plan the long journey from Bandaranaike Airport to Arugam Bay with a suitable private vehicle and a confirmed pickup plan."}
};
export function AirportRoutePage({slug}:{slug:string}){const r=routeData[slug];const title=`Colombo Airport to ${r.destination} Transfer | Radesha Tours`;const description=`Book a private Colombo Airport to ${r.destination} transfer with Radesha Tours. Flight-aware pickup, suitable vehicles and easy WhatsApp confirmation.`;const service={"@context":"https://schema.org","@type":"Service",name:`Colombo Airport to ${r.destination} private transfer`,provider:{"@type":"TravelAgency",name:"Radesha Tours",url:"https://radeshatours.com/"},areaServed:"Sri Lanka"};return <><SeoHead title={title} description={description} path={`/airport-transfer/${slug}`} schema={service}/><section className="section section-muted"><div className="container"><Breadcrumbs items={[{label:"Airport Transfers",to:"/airport-transfer"},{label:`Colombo Airport to ${r.destination}`}]}/><div className="eyebrow">Private airport transfer</div><h1>Colombo Airport to {r.destination} Transfer</h1><p>{r.description}</p><div className="cards-3 seo-facts"><div className="card card-body"><MapPin/><h3>Route</h3><p>Bandaranaike International Airport to {r.destination}</p></div><div className="card card-body"><Car/><h3>Distance</h3><p>{r.distance}</p></div><div className="card card-body"><Clock/><h3>Travel time</h3><p>{r.duration}</p></div></div></div></section><SeoDetails type="transfer" destination={r.destination}/></>}

const safariData:Record<string,{name:string;overview:string}>={
 "yala-national-park":{name:"Yala National Park",overview:"Plan a private Yala safari with pickup coordination, safari jeep guidance, and onward transport support."},
 "udawalawe-national-park":{name:"Udawalawe National Park",overview:"Arrange an Udawalawe safari focused on practical timing, private travel, and a simple booking process."},
 "bundala-national-park":{name:"Bundala National Park",overview:"Explore Bundala’s wetlands and birdlife with route planning and private pickup support."},
 "kumana-national-park":{name:"Kumana National Park",overview:"Plan a Kumana safari for east-coast landscapes and birdlife with custom pickup arrangements."},
 "ella-to-yala":{name:"Ella to Yala Safari",overview:"Combine private transport from Ella with a planned Yala safari and return or onward travel."},
 "ella-to-udawalawe":{name:"Ella to Udawalawe Safari",overview:"Arrange an Udawalawe safari from Ella with pickup timing and safari options confirmed in advance."}
};
export function SafariLandingPage({slug}:{slug:string}){const s=safariData[slug];const description=`Book a private ${s.name} experience with Radesha Tours, including local route planning and easy WhatsApp booking.`;return <><SeoHead title={`${s.name} Tours | Radesha Tours Ella`} description={description} path={`/safari/${slug}`} schema={{"@context":"https://schema.org","@type":"Service",name:s.name,provider:{"@type":"TravelAgency",name:"Radesha Tours"},areaServed:"Sri Lanka"}}/><section className="section section-muted"><div className="container"><Breadcrumbs items={[{label:"Safari Tours",to:"/safari"},{label:s.name}]}/><div className="eyebrow">Sri Lanka safari</div><h1>{s.name}</h1><p>{s.overview}</p></div></section><SeoDetails type="safari" destination={s.name}/></>}

export function RentalLandingPage({type}:{type:"car"|"scooter"}){const name=type==="car"?"Car Rental Ella":"Scooter Rental Ella";const description=`Arrange ${name.toLowerCase()} with Radesha Tours. Ask about available vehicles, rental requirements, pickup details and current rates on WhatsApp.`;return <><SeoHead title={`${name} Sri Lanka | Radesha Tours`} description={description} path={`/${type}-rental-ella`} schema={{"@context":"https://schema.org","@type":"Service",name,provider:{"@type":"TravelAgency",name:"Radesha Tours"},areaServed:"Ella, Sri Lanka"}}/><section className="section section-muted"><div className="container"><Breadcrumbs items={[{label:"Vehicle Rentals",to:"/rent-vehicles"},{label:name}]}/><div className="eyebrow">Vehicle rental in Ella</div><h1>{name}</h1><p>Contact Radesha Tours to check current vehicle availability, rental requirements, pickup arrangements, and rates. We keep booking simple through WhatsApp.</p></div></section><SeoDetails type="rental" destination={name}/></>}

function SeoDetails({type,destination}:{type:string;destination:string}){const items=type==="safari"?["Pickup location and preferred date","Half-day or full-day options where available","Safari jeep and transport coordination","What to bring and timing guidance"]:type==="rental"?["Current vehicle availability","Rental requirements","Pickup and return details","Passenger or luggage needs"]:["Flight number and arrival time","Passenger and luggage count","Private vehicle selection","Pickup instructions and delay support"];return <><section className="section"><div className="container hero-grid"><article><h2>Plan your {destination} booking</h2><p>Send your travel date and requirements so the Radesha Tours team can confirm the most suitable option. Current rates and availability are provided directly without publishing outdated information.</p><a className="btn btn-green" href={`https://wa.me/94758110086?text=${encodeURIComponent(`Hello Radesha Tours, I would like to book ${destination}.`)}`}><MessageCircle size={16}/>Ask on WhatsApp</a></article><div className="feature-list">{items.map(x=><div className="feature-box" key={x}><CheckCircle2/>{x}</div>)}</div></div></section><section className="section section-dark"><div className="container"><h2>Frequently asked questions</h2><div className="cards-3"><article className="dark-card"><h3>How do I book?</h3><p>Message Radesha Tours on WhatsApp with your date, pickup point, destination, and group details.</p></article><article className="dark-card"><h3>Can pickup be arranged?</h3><p>Share your hotel or arrival location so the team can confirm available pickup arrangements.</p></article><article className="dark-card"><h3>When is my booking confirmed?</h3><p>Your booking is confirmed after the route or service details, timing, availability, and rate are agreed directly.</p></article></div><div className="related"><Link to="/airport-transfer">Airport transfers</Link><Link to="/safari">Sri Lanka safaris</Link><Link to="/rent-vehicles">Vehicle rentals</Link></div></div></section></>}

export function NotFound(){return <><SeoHead title="Page Not Found | Radesha Tours" description="The requested Radesha Tours page could not be found."/><section className="section section-muted"><div className="container"><div className="eyebrow">404 error</div><h1>We could not find that page</h1><p>Use one of the links below to continue planning your Sri Lanka journey.</p><div className="actions"><Link className="btn btn-dark" to="/">Home</Link><Link className="btn btn-dark" to="/airport-transfer">Airport Transfers</Link><Link className="btn btn-dark" to="/safari">Safari</Link><Link className="btn btn-dark" to="/rent-vehicles">Vehicle Rentals</Link></div></div></section></>}
