import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const site="https://radeshatours.com";
const pages=[
 ["/","Radesha Tours Ella | Sri Lanka Tours, Transfers & Rentals","Explore Sri Lanka with Radesha Tours Ella. Book private airport transfers, safari tours, car rentals, scooter rentals and custom Sri Lanka tours with easy WhatsApp booking.","Ella Tours, Transfers & Rentals Across Sri Lanka"],
 ["/airport-transfer","Sri Lanka Airport Transfers | Private Airport Taxi | Radesha Tours","Book reliable private airport transfers from Bandaranaike International Airport to Ella, Kandy, Galle, Mirissa, Yala, Arugam Bay and destinations across Sri Lanka.","Reliable airport transfers across Sri Lanka"],
 ["/hire-rates","Sri Lanka Airport Transfer Routes | Private Taxi Quotes","Explore airport transfer routes from Colombo Bandaranaike Airport to popular Sri Lankan destinations including Ella, Kandy, Galle, Mirissa and Arugam Bay.","Airport transfer routes from Katunayake Airport"],
 ["/safari","Sri Lanka Safari Tours | Yala & Udawalawe Safari | Radesha Tours","Book private Sri Lanka safari tours to Yala, Udawalawe, Bundala and Kumana National Parks with local drivers, safari jeeps and easy WhatsApp booking.","Safari adventures planned around your journey"],
 ["/rent-vehicles","Car & Scooter Rental Ella Sri Lanka | Radesha Tours","Rent cars, SUVs, sedans and scooters in Ella, Sri Lanka with simple WhatsApp booking.","Car and scooter rental in Ella Sri Lanka"],
 ["/about","About Radesha Tours | Local Travel Service in Ella Sri Lanka","Learn about Radesha Tours, a local Ella-based travel service offering airport transfers, Sri Lanka tours, safaris and vehicle rentals.","About Radesha Tours"],
];
const transfer=["ella","kandy","galle","mirissa","arugam-bay"];
for(const destination of transfer){const label=destination.split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ");pages.push([`/airport-transfer/colombo-airport-to-${destination}`,`Colombo Airport to ${label} Transfer | Radesha Tours`,`Book a private Colombo Airport to ${label} transfer with Radesha Tours and confirm pickup details on WhatsApp.`,`Colombo Airport to ${label} Transfer`])}
for(const slug of ["yala-national-park","udawalawe-national-park","bundala-national-park","kumana-national-park","ella-to-yala","ella-to-udawalawe"]){const label=slug.split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ");pages.push([`/safari/${slug}`,`${label} Safari | Radesha Tours`,`Plan a private ${label} safari with local route support and easy WhatsApp booking.`,label])}
pages.push(["/car-rental-ella","Car Rental Ella Sri Lanka | Radesha Tours","Ask about car rentals in Ella, vehicle availability, requirements and pickup details.","Car Rental Ella"],["/scooter-rental-ella","Scooter Rental Ella Sri Lanka | Radesha Tours","Ask about scooter rentals in Ella, availability, requirements and pickup details.","Scooter Rental Ella"]);
const template=await readFile("dist/index.html","utf8");
const esc=s=>s.replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
for(const [path,title,description,h1] of pages){const canonical=`${site}${path==="/"?"/":path}`;const crumbs=path.split("/").filter(Boolean);const schema=path==="/"?{"@context":"https://schema.org","@graph":[{"@type":"TravelAgency",name:"Radesha Tours",url:`${site}/`,telephone:"+94758110086",email:"info@radeshatours.com",address:{"@type":"PostalAddress",addressLocality:"Ella",addressCountry:"LK"},areaServed:"Sri Lanka"},{"@type":"WebSite",name:"Radesha Tours",url:`${site}/`}]}:{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:`${site}/`},...crumbs.map((part,index)=>({"@type":"ListItem",position:index+2,name:part.replace(/-/g," "),item:`${site}/${crumbs.slice(0,index+1).join("/")}`}))]};let html=template.replace(/<title>.*?<\/title>/,`<title>${esc(title)}</title>`).replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${esc(description)}">`).replace("</head>",`<link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:type" content="website"><meta property="og:image" content="https://images.pexels.com/photos/12147639/pexels-photo-12147639.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1200&amp;h=630&amp;fit=crop"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,"\\u003c")}</script></head>`).replace('<div id="root"></div>',`<div id="root"><main><h1>${esc(h1)}</h1><p>${esc(description)}</p><nav><a href="/">Home</a> <a href="/airport-transfer">Airport Transfers</a> <a href="/safari">Safari Tours</a> <a href="/rent-vehicles">Vehicle Rentals</a></nav></main></div>`);const file=path==="/"?"dist/index.html":join("dist",path.slice(1),"index.html");await mkdir(dirname(file),{recursive:true});await writeFile(file,html)}
const notFound=template.replace(/<title>.*?<\/title>/,"<title>Page Not Found | Radesha Tours</title>").replace(/<meta name="robots"[^>]*>/,'<meta name="robots" content="noindex, follow">').replace('<div id="root"></div>','<div id="root"><main><h1>Page not found</h1><p>Return to Radesha Tours to plan airport transfers, safaris, and vehicle rentals.</p><a href="/">Return home</a></main></div>');await writeFile("dist/404.html",notFound);
console.log(`Prerendered ${pages.length} SEO pages.`);
